### ISSUE TITLE
Chrome  49.0.2593.0 dev-m (64-bit)

### ISSUE THREAD

**Issue by incon** [mac-cain13/xdebug-helper-for-chrome#55]
Clicking on an option in the popup

extensions::uncaught_exception_handler:8 Error in response to runtime.getBackgroundPage: TypeError: Cannot read property 'status' of undefined
    at chrome-extension://eadndfjplgieldjbigjakmdgkmoaaaoc/popup.js:45:41
    at chrome-extension://eadndfjplgieldjbigjakmdgkmoaaaoc/popup.js:44:21

**Comment by incon** [comment]
Doesn't have to do with the chrome version
